volumes:
  data:
services:
  db:
    image: linuxserver/mariadb:arm32v7-alpine-10.5.16-r0-ls63
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  admin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80









